from PIL import Image
import numpy as np
import sys

# this just makes it so that the matrices aren't printed out w/ ellipses, but for readability, I turned it off
# np.set_printoptions(threshold=sys.maxsize)


'''
1. Open an image
2. Take each pixel and change to an rgb value
    make a matrix of rgb values using numpy
3. Observe original matrix values
4. Scale image using scaling algorithm
5. Observe new matrix values

6. Find the coefficients of the matrix?
'''

im = Image.open('black_star.jpg')
width, height = im.size

# convert image into an array of rgb values
pixel_values = list(im.getdata()) # gets rgb values

# creates a numpy array from the list generated by getdata()
# reshape just makes it so that the array dimensions match the image dimensions
m = np.asarray(pixel_values).reshape((width, height))

# keep track of data in console
print('og img matrix:\n', m, '\n')
print('num of pixels in og img: ', m.size)
print('og img dimensions: ', m.shape, '\n')


new_size = (200, 200)

# Image.resize(size, resample)
im1 = im.resize(new_size, resample=Image.NEAREST)
im2 = im.resize(new_size, resample=Image.BILINEAR)

im2_pixelv = list(im1.getdata())
m2 = np.asarray(im2_pixelv).reshape(new_size)
print('matrix of scaled img using NN: \n', m2, '\n')

# keep track of data in console
print('num of pixels in scaled img: ', m2.size)
print('scaled img dimensions: ', m2.shape)


